spring:
    thymeleaf: # Thymeleaf
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: file:src/main/resources/templates/
    resources: # Static resources
        static-locations: file:src/main/resources/static/
        cache:
            period: 0
    datasource:
        password: yE6rktqU;_KCt/;P
        url: jdbc:mysql://boopr.dog/boopr?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: pon
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
    devtools:
        livereload:
            enabled: true 
image-upload-path : images/
mapbox-key : pk.eyJ1IjoiaGV5bG9va2FzcXVpcnJlbCIsImEiOiJja2lpemlscmowMzA5MnRxY3FrbDFlcmJmIn0.CGcu-JA1me1Eyxu9-LJX1Q 